# Generated by Django 3.2.20 on 2023-10-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('faild', 'Faild')], max_length=100, null=True),
        ),
    ]
