# Generated by Django 3.2.20 on 2024-08-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_paymentlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='show_buyer_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='show_buyer_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='show_card_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='show_fund_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='show_promise_option',
            field=models.BooleanField(default=True),
        ),
    ]
