# Generated by Django 3.2.20 on 2024-08-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20240815_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
