# Generated by Django 3.2.20 on 2024-08-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_paymentlink_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
