# Generated by Django 3.2.20 on 2024-08-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_paymentlink_payment_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
    ]
