# Generated by Django 3.2.20 on 2024-08-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_paymentlink_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='payment_link',
            field=models.CharField(max_length=225, null=True, unique=True),
        ),
    ]
