# Generated by Django 3.2.20 on 2024-08-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_paymentlink_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='payment_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment/img/'),
        ),
    ]
