# Generated by Django 3.2.20 on 2024-08-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_paymentlink_payment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='qty',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='show_qty',
            field=models.BooleanField(default=False),
        ),
    ]
