# Generated by Django 3.2.20 on 2024-08-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20240820_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='qty',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
