# Generated by Django 3.2.20 on 2024-08-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_alter_paymentlink_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
