# Generated by Django 3.2.20 on 2023-10-02 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fund_account', '0003_accountfundbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountfundbalance',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='fundaccount',
            name='seller',
        ),
        migrations.AddField(
            model_name='accountfundbalance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_account_balance_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_account_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
