# Generated by Django 3.2.20 on 2023-10-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_account', '0004_auto_20231002_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountfundbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
