# Generated by Django 3.2.20 on 2023-10-02 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fund_account', '0005_alter_accountfundbalance_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitAccountFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, choices=[('NGN', 'Nigerian Naira'), ('USD', 'United States Dollar'), ('GBP', 'British Pound Sterling'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('ZAR', 'South African Rand'), ('BRL', 'Brazilian Real'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi'), ('AED', 'United Arab Emirates Dirham'), ('SAR', 'Saudi Riyal'), ('GBP', 'British Pound Sterling')], max_length=3, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('google_pay', 'Google Pay'), ('apple_pay', 'Apple Pay')], max_length=50, null=True)),
                ('payment_provider', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('gtb', 'GTB'), ('fidelity', 'Fidelity')], max_length=50)),
                ('debit_account_id', models.CharField(max_length=10, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_account_debit_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
