# Generated by Django 3.2.20 on 2023-10-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_account', '0006_debitaccountfund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundaccount',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('gtb', 'GTB'), ('fidelity', 'Fidelity')], max_length=50, null=True),
        ),
    ]
