# Generated by Django 3.2.20 on 2023-11-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_account', '0008_fundaccountcreditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountfundbalance',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountfundbalance',
            name='max_withdrawal',
            field=models.DecimalField(decimal_places=2, default=2000000, max_digits=16),
        ),
        migrations.AlterField(
            model_name='accountfundbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
