# Generated by Django 3.2.20 on 2023-11-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_account', '0014_alter_accountfundbalance_max_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundaccount',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
