# Generated by Django 3.2.20 on 2023-11-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_account', '0017_auto_20231110_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountfundbalance',
            name='is_diabled',
            field=models.BooleanField(default=False),
        ),
    ]
