# Generated by Django 3.2.20 on 2023-11-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_account', '0018_accountfundbalance_is_diabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountfundbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
        migrations.AlterField(
            model_name='debitaccountfund',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='debitaccountfund',
            name='debit_account_id',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fundaccount',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=16, null=True),
        ),
    ]
