# Generated by Django 3.2.20 on 2023-11-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_account', '0019_auto_20231118_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitaccountfund',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Debit Card', 'Debit Card'), ('Paysofter Account Fund', 'Paysofter Account Fund'), ('Paysofter Promise', 'Paysofter Promise'), ('Bank', 'Bank'), ('Transfer', 'Transfer'), ('QR COde', 'QR COde'), ('USSD', 'USSD')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='debitaccountfund',
            name='payment_provider',
            field=models.CharField(choices=[('Paysofter', 'Paysofter'), ('Mastercard', 'Mastercard'), ('Verve', 'Verve'), ('Visa', 'Visa'), ('GTB', 'GTB'), ('Fidelity', 'Fidelity')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fundaccount',
            name='currency',
            field=models.CharField(blank=True, choices=[('NGN', 'Nigerian Naira'), ('USD', 'United States Dollar'), ('GBP', 'British Pound Sterling'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('ZAR', 'South African Rand'), ('BRL', 'Brazilian Real'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi'), ('AED', 'United Arab Emirates Dirham'), ('SAR', 'Saudi Riyal'), ('GBP', 'British Pound Sterling')], default='NGN', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fundaccount',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Debit Card', 'Debit Card'), ('Paysofter Account Fund', 'Paysofter Account Fund'), ('Paysofter Promise', 'Paysofter Promise'), ('Bank', 'Bank'), ('Transfer', 'Transfer'), ('QR COde', 'QR COde'), ('USSD', 'USSD')], default='Debit Card', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fundaccount',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('Paysofter', 'Paysofter'), ('Mastercard', 'Mastercard'), ('Verve', 'Verve'), ('Visa', 'Visa'), ('GTB', 'GTB'), ('Fidelity', 'Fidelity')], max_length=50, null=True),
        ),
    ]
