# Generated by Django 3.2.20 on 2023-12-30 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fund_account', '0020_auto_20231118_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsdAccountFundBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('max_withdrawal', models.DecimalField(blank=True, choices=[(10, 'Less than 10'), (100, 'Less than 100'), (500, 'Less than 500'), (1000, 'Less than 1,000'), (2000, 'Less than 2,000'), (5000, 'Less than 5,000'), (10000, 'Less than 10,000'), (1000000, 'More than 10,000')], decimal_places=2, default=1000, max_digits=16, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_diabled', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usd_balance_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FundUsdAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=16, null=True)),
                ('currency', models.CharField(blank=True, choices=[('NGN', 'Nigerian Naira'), ('USD', 'United States Dollar'), ('GBP', 'British Pound Sterling'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('ZAR', 'South African Rand'), ('BRL', 'Brazilian Real'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi'), ('AED', 'United Arab Emirates Dirham'), ('SAR', 'Saudi Riyal'), ('GBP', 'British Pound Sterling')], default='USD', max_length=3, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('Debit Card', 'Debit Card'), ('Paysofter Account Fund', 'Paysofter Account Fund'), ('Paysofter Promise', 'Paysofter Promise'), ('Bank', 'Bank'), ('Transfer', 'Transfer'), ('QR COde', 'QR COde'), ('USSD', 'USSD')], default='Debit Card', max_length=50, null=True)),
                ('payment_provider', models.CharField(blank=True, choices=[('Paysofter', 'Paysofter'), ('Mastercard', 'Mastercard'), ('Verve', 'Verve'), ('Visa', 'Visa'), ('GTB', 'GTB'), ('Fidelity', 'Fidelity')], max_length=50, null=True)),
                ('fund_account_id', models.CharField(max_length=10, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usd_fund_account_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DebitUsdAccountFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, choices=[('NGN', 'Nigerian Naira'), ('USD', 'United States Dollar'), ('GBP', 'British Pound Sterling'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('ZAR', 'South African Rand'), ('BRL', 'Brazilian Real'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi'), ('AED', 'United Arab Emirates Dirham'), ('SAR', 'Saudi Riyal'), ('GBP', 'British Pound Sterling')], max_length=3, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('Debit Card', 'Debit Card'), ('Paysofter Account Fund', 'Paysofter Account Fund'), ('Paysofter Promise', 'Paysofter Promise'), ('Bank', 'Bank'), ('Transfer', 'Transfer'), ('QR COde', 'QR COde'), ('USSD', 'USSD')], max_length=50, null=True)),
                ('payment_provider', models.CharField(choices=[('Paysofter', 'Paysofter'), ('Mastercard', 'Mastercard'), ('Verve', 'Verve'), ('Visa', 'Visa'), ('GTB', 'GTB'), ('Fidelity', 'Fidelity')], max_length=50)),
                ('debit_account_id', models.CharField(editable=False, max_length=10, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usd_fund_account_debit_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
