# Generated by Django 3.2.20 on 2023-12-30 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund_account', '0021_debitusdaccountfund_fundusdaccount_usdaccountfundbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsdFundAccountCreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_month_year', models.CharField(blank=True, max_length=100, null=True)),
                ('cvv', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fund_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usd_credit_card', to='fund_account.fundusdaccount')),
            ],
        ),
    ]
