# Generated by Django 3.2.20 on 2024-02-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund_account', '0024_currencychoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyChoice',
        ),
    ]
