# Generated by Django 3.2.20 on 2024-07-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_account', '0026_auto_20240625_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitaccountfund',
            name='debit_account_id',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='debitusdaccountfund',
            name='debit_account_id',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fundaccount',
            name='fund_account_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fundusdaccount',
            name='fund_account_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
