# Generated by Django 3.2.20 on 2024-07-21 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fund_account', '0027_auto_20240720_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDebitAccountFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, choices=[('NGN', 'Nigerian Naira'), ('USD', 'United States Dollar'), ('GBP', 'British Pound Sterling'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('ZAR', 'South African Rand'), ('BRL', 'Brazilian Real'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi'), ('AED', 'United Arab Emirates Dirham'), ('SAR', 'Saudi Riyal'), ('GBP', 'British Pound Sterling')], max_length=3, null=True)),
                ('old_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_success', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('Debit Card', 'Debit Card'), ('Paysofter Account Fund', 'Paysofter Account Fund'), ('Paysofter Promise', 'Paysofter Promise'), ('Bank', 'Bank'), ('Transfer', 'Transfer'), ('QR COde', 'QR COde'), ('USSD', 'USSD')], max_length=50, null=True)),
                ('payment_provider', models.CharField(choices=[('Paysofter', 'Paysofter'), ('Mastercard', 'Mastercard'), ('Verve', 'Verve'), ('Visa', 'Visa'), ('GTB', 'GTB'), ('Fidelity', 'Fidelity')], max_length=50)),
                ('debit_account_id', models.CharField(editable=False, max_length=50, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_account_debit_user_test', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
