# Generated by Django 3.2.20 on 2024-07-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_account', '0028_testdebitaccountfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdebitaccountfund',
            name='buyer_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
