# Generated by Django 3.2.20 on 2024-08-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_account', '0030_auto_20240825_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundaccount',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='fundusdaccount',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='debitaccountfund',
            name='product_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='debitaccountfund',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='debitaccountfund',
            name='reference_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='debitusdaccountfund',
            name='product_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='debitusdaccountfund',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='debitusdaccountfund',
            name='reference_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
