# Generated by Django 3.2.20 on 2023-11-22 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOwnerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvn', models.CharField(blank=True, max_length=10, null=True)),
                ('id_type', models.CharField(blank=True, choices=[('NIN', 'NIN'), ('Intl Passport', 'Intl Passport'), ('Driving License', 'Driving License'), ('Govt Issued ID', 'Govt Issued ID')], max_length=50, null=True)),
                ('id_number', models.CharField(blank=True, max_length=30, null=True)),
                ('id_card_image', models.ImageField(upload_to='media/sellers/')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.CharField(blank=True, max_length=225, null=True)),
                ('address', models.CharField(blank=True, max_length=225, null=True)),
                ('proof_of_address', models.ImageField(upload_to='media/sellers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('director_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/sellers/')),
                ('business_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_owner', to='sellers.businessownerdetail')),
            ],
        ),
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('trading_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_business_registered', models.BooleanField(default=False)),
                ('business_reg_num', models.CharField(blank=True, max_length=50, null=True)),
                ('business_address', models.CharField(blank=True, max_length=225, null=True)),
                ('business_type', models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Unregistered', 'Unregistered')], max_length=225, null=True)),
                ('staff_size', models.CharField(blank=True, choices=[('Small', 'Small (1-50 employees)'), ('Medium', 'Medium (51-250 employees)'), ('Large', 'Large (251+ employees)')], max_length=50, null=True)),
                ('business_industry', models.CharField(blank=True, choices=[('Information Technology', 'Information Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Education', 'Education'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Services', 'Services'), ('Entertainment', 'Entertainment'), ('Food', 'Food & Beverage'), ('Travel', 'Travel & Tourism'), ('Real Estate', 'Real Estate'), ('Construction', 'Construction'), ('Automotive', 'Automotive'), ('Agriculture', 'Agriculture'), ('Energy', 'Energy'), ('Environmental', 'Environmental'), ('Government', 'Government'), ('Nonprofit', 'Nonprofit'), ('Others', 'Others')], max_length=50, null=True)),
                ('business_category', models.CharField(blank=True, choices=[('Startup', 'Startup'), ('Small Business', 'Small Business'), ('Medium Business', 'Medium Business'), ('Large Business', 'Large Business'), ('Corporation', 'Corporation'), ('Sole Proprietorship', 'Sole Proprietorship'), ('Partnership', 'Partnership'), ('Franchise', 'Franchise'), ('Family Owned', 'Family Owned'), ('Online Business', 'Online Business'), ('Brick and Mortar', 'Brick and Mortar'), ('Service Provider', 'Service Provider'), ('Retailer', 'Retailer'), ('Wholesaler', 'Wholesaler'), ('Manufacturer', 'Manufacturer'), ('Restaurant', 'Restaurant'), ('Hospitality', 'Hospitality'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Tech', 'Tech'), ('Creative', 'Creative'), ('Entertainment', 'Entertainment'), ('Travel', 'Travel'), ('Construction', 'Construction'), ('Automotive', 'Automotive'), ('Agriculture', 'Agriculture'), ('Energy', 'Energy'), ('Environmental', 'Environmental'), ('Government', 'Government'), ('Nonprofit', 'Nonprofit'), ('Others', 'Others')], max_length=50, null=True)),
                ('business_description', models.TextField(blank=True, max_length=225, null=True)),
                ('business_website', models.CharField(blank=True, max_length=225, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_account_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='businessownerdetail',
            name='seller_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_account', to='sellers.selleraccount'),
        ),
    ]
