# Generated by Django 3.2.20 on 2023-11-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleraccount',
            name='business_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
