# Generated by Django 3.2.20 on 2023-11-23 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellers', '0004_alter_selleraccount_business_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessownerdetail',
            name='phone',
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='business_email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='business_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='support_email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_account_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_bank_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businessownerdetail',
            name='id_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='selleraccount',
            name='business_address',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='selleraccount',
            name='business_category',
            field=models.CharField(choices=[('Startup', 'Startup'), ('Small Business', 'Small Business'), ('Medium Business', 'Medium Business'), ('Large Business', 'Large Business'), ('Corporation', 'Corporation'), ('Sole Proprietorship', 'Sole Proprietorship'), ('Partnership', 'Partnership'), ('Franchise', 'Franchise'), ('Family Owned', 'Family Owned'), ('Online Business', 'Online Business'), ('Brick and Mortar', 'Brick and Mortar'), ('Service Provider', 'Service Provider'), ('Retailer', 'Retailer'), ('Wholesaler', 'Wholesaler'), ('Manufacturer', 'Manufacturer'), ('Restaurant', 'Restaurant'), ('Hospitality', 'Hospitality'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Tech', 'Tech'), ('Creative', 'Creative'), ('Entertainment', 'Entertainment'), ('Travel', 'Travel'), ('Construction', 'Construction'), ('Automotive', 'Automotive'), ('Agriculture', 'Agriculture'), ('Energy', 'Energy'), ('Environmental', 'Environmental'), ('Government', 'Government'), ('Nonprofit', 'Nonprofit'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selleraccount',
            name='business_industry',
            field=models.CharField(choices=[('Information Technology', 'Information Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Education', 'Education'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Services', 'Services'), ('Entertainment', 'Entertainment'), ('Food', 'Food & Beverage'), ('Travel', 'Travel & Tourism'), ('Real Estate', 'Real Estate'), ('Construction', 'Construction'), ('Automotive', 'Automotive'), ('Agriculture', 'Agriculture'), ('Energy', 'Energy'), ('Environmental', 'Environmental'), ('Government', 'Government'), ('Nonprofit', 'Nonprofit'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selleraccount',
            name='business_type',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Unregistered', 'Unregistered')], max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='selleraccount',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_account_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='selleraccount',
            name='staff_size',
            field=models.CharField(choices=[('Small', 'Small (1-50 employees)'), ('Medium', 'Medium (51-250 employees)'), ('Large', 'Large (251+ employees)')], max_length=50, null=True),
        ),
    ]
