# Generated by Django 3.2.20 on 2023-11-23 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellers', '0005_auto_20231123_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessownerdetail',
            name='bvn',
        ),
        migrations.CreateModel(
            name='BankVerificationNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvn', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bvn_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
