# Generated by Django 3.2.20 on 2023-11-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_auto_20231123_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessownerdetail',
            name='director_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
