# Generated by Django 3.2.20 on 2023-11-24 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellers', '0007_alter_businessownerdetail_director_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerphoto',
            name='business_owner',
        ),
        migrations.AddField(
            model_name='sellerphoto',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
