# Generated by Django 3.2.20 on 2023-11-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0008_auto_20231124_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selleraccount',
            old_name='is_terms_conditions_read',
            new_name='is_seller_verified',
        ),
    ]
