# Generated by Django 3.2.20 on 2023-11-30 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellers', '0009_rename_is_terms_conditions_read_selleraccount_is_seller_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessownerdetail',
            name='seller_account',
        ),
        migrations.AddField(
            model_name='businessownerdetail',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_owner_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
