# Generated by Django 3.2.20 on 2023-12-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0010_auto_20231130_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
