# Generated by Django 3.2.20 on 2023-12-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0011_selleraccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='business_reg_cert',
            field=models.ImageField(blank=True, null=True, upload_to='media/sellers/'),
        ),
    ]
