# Generated by Django 3.2.20 on 2023-12-01 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellers', '0012_selleraccount_business_reg_cert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleraccount',
            name='business_reg_cert',
        ),
        migrations.RemoveField(
            model_name='selleraccount',
            name='is_business_registered',
        ),
        migrations.CreateModel(
            name='BusinessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_business_registered', models.BooleanField(default=False)),
                ('business_name', models.CharField(max_length=100, null=True)),
                ('business_reg_num', models.CharField(blank=True, max_length=50, null=True)),
                ('business_reg_cert', models.ImageField(blank=True, null=True, upload_to='media/sellers/')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_status_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
