# Generated by Django 3.2.20 on 2023-12-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0013_auto_20231201_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessstatus',
            name='business_status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Unregistered', 'Unregistered')], max_length=225, null=True),
        ),
    ]
