# Generated by Django 3.2.20 on 2023-12-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0014_businessstatus_business_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessstatus',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessstatus',
            name='business_status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Unregistered', 'Unregistered')], default='Unregistered', max_length=225, null=True),
        ),
    ]
