# Generated by Django 3.2.20 on 2023-12-20 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellers', '0015_auto_20231201_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_bank_account_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankverificationnumber',
            name='is_bvn_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UsdBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100, null=True)),
                ('bank_account_number', models.CharField(max_length=10, null=True)),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('is_usd_bank_account_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_usd_bank_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
