# Generated by Django 3.2.20 on 2023-12-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0016_auto_20231220_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessstatus',
            name='is_business_verified',
            field=models.BooleanField(default=False),
        ),
    ]
