# Generated by Django 3.2.20 on 2024-05-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0017_businessstatus_is_business_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleraccount',
            name='business_email',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='selleraccount',
            name='business_phone',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='selleraccount',
            name='country',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='selleraccount',
            name='support_email',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
