# Generated by Django 3.2.20 on 2024-08-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0018_auto_20240509_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/sellers/'),
        ),
    ]
