# Generated by Django 3.2.20 on 2024-08-24 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellers', '0020_remove_selleraccount_is_seller_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_verified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
