# Generated by Django 3.2.20 on 2023-11-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysofterpromise',
            name='payer_promise_fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paysofterpromise',
            name='seller_fulfilled_promise',
            field=models.BooleanField(default=False),
        ),
    ]
