# Generated by Django 3.2.20 on 2023-11-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0002_auto_20231110_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysofterpromise',
            name='duration',
            field=models.CharField(blank=True, choices=[('1day', '1 day'), ('2days', 'Less than 2 days'), ('3days', 'Less than 3 days'), ('1week', 'Less than 1 week'), ('2week', 'Less than 2 weeks'), ('1month', 'Less than 1 month')], default='1day', max_length=50, null=True),
        ),
    ]
