# Generated by Django 3.2.20 on 2023-11-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0003_paysofterpromise_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysofterpromise',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('debit_card', 'Debit Card'), ('paysofter_account_fund', 'Paysofter Account Fund'), ('paysofter_promise', 'Paysofter Promise'), ('bank', 'Bank'), ('transfer', 'Transfer'), ('qrcode', 'QR COde'), ('USSD', 'USSD')], max_length=50, null=True),
        ),
    ]
