# Generated by Django 3.2.20 on 2023-11-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0004_alter_paysofterpromise_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysofterpromise',
            name='payment_provider',
            field=models.CharField(choices=[('paysofter', 'Paysofter'), ('mastercard', 'Mastercard'), ('verve', 'Verve'), ('visa', 'Visa'), ('gtb', 'GTB'), ('fidelity', 'Fidelity')], max_length=50),
        ),
    ]
