# Generated by Django 3.2.20 on 2023-11-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0005_alter_paysofterpromise_payment_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paysofterpromise',
            old_name='payer',
            new_name='buyer',
        ),
    ]
