# Generated by Django 3.2.20 on 2023-11-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0008_auto_20231112_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paysofterpromise',
            old_name='payer_promise_fulfilled',
            new_name='buyer_promise_fulfilled',
        ),
        migrations.AlterField(
            model_name='paysofterpromise',
            name='status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Fulfilled', 'Fulfilled'), ('Failed', 'Failed')], max_length=100, null=True),
        ),
    ]
