# Generated by Django 3.2.20 on 2023-11-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0009_auto_20231112_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysofterpromise',
            name='currency',
            field=models.CharField(blank=True, choices=[('NGN', 'NGN'), ('USD', 'USD'), ('GBP', 'British Pound Sterling'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('ZAR', 'South African Rand'), ('BRL', 'Brazilian Real'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi'), ('AED', 'United Arab Emirates Dirham'), ('SAR', 'Saudi Riyal')], default='NGN', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='paysofterpromise',
            name='duration',
            field=models.CharField(blank=True, choices=[('Within 1 day', 'Within 1 day'), ('2 days', 'Less than 2 days'), ('3 days', 'Less than 3 days'), ('1 week', 'Less than 1 week'), ('2 week', 'Less than 2 weeks'), ('1 month', 'Less than 1 month')], default='Within 1 day', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paysofterpromise',
            name='status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Fulfilled', 'Fulfilled'), ('Failed', 'Failed')], default='Processing', max_length=100, null=True),
        ),
    ]
