# Generated by Django 3.2.20 on 2023-11-13 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promise', '0010_auto_20231112_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysofterpromise',
            name='payment_provider',
            field=models.CharField(choices=[('Paysofter', 'Paysofter'), ('Mastercard', 'Mastercard'), ('Verve', 'Verve'), ('Visa', 'Visa'), ('GTB', 'GTB'), ('Fidelity', 'Fidelity')], max_length=100),
        ),
        migrations.CreateModel(
            name='SellerPromiseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=5000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promise_message_seller', to=settings.AUTH_USER_MODEL)),
                ('seller_promise_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_promise_message', to='promise.paysofterpromise')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerPromiseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=5000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promise_message_buyer', to=settings.AUTH_USER_MODEL)),
                ('buyer_promise_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_promise_message', to='promise.paysofterpromise')),
            ],
        ),
    ]
