# Generated by Django 3.2.20 on 2023-11-14 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promise', '0011_auto_20231113_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromiseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=225, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_promise_message', to=settings.AUTH_USER_MODEL)),
                ('promise_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promise_message', to='promise.paysofterpromise')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_promise_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sellerpromisemessage',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='sellerpromisemessage',
            name='seller_promise_message',
        ),
        migrations.DeleteModel(
            name='BuyerPromiseMessage',
        ),
        migrations.DeleteModel(
            name='SellerPromiseMessage',
        ),
    ]
