# Generated by Django 3.2.20 on 2023-11-14 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promise', '0012_auto_20231114_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promisemessage',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='promisemessage',
            name='seller',
        ),
        migrations.AddField(
            model_name='promisemessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promise_message_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
