# Generated by Django 3.2.20 on 2023-11-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0014_paysofterpromise_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysofterpromise',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
