# Generated by Django 3.2.20 on 2023-11-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0016_auto_20231117_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysofterpromise',
            name='duration',
            field=models.CharField(blank=True, choices=[('0 day', '0 day'), ('Within 1 day', 'Within 1 day'), ('2 days', 'Less than 2 days'), ('3 days', 'Less than 3 days'), ('5 days', 'Less than 5 days'), ('1 week', 'Less than 1 week'), ('2 week', 'Less than 2 weeks'), ('1 month', 'Less than 1 month')], default='Within 1 day', max_length=100, null=True),
        ),
    ]
