# Generated by Django 3.2.20 on 2023-11-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0018_alter_paysofterpromise_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysofterpromise',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
