# Generated by Django 3.2.20 on 2023-11-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0019_paysofterpromise_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysofterpromise',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='paysofterpromise',
            name='promise_id',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
    ]
