# Generated by Django 3.2.20 on 2023-11-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0020_auto_20231118_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysofterpromise',
            name='is_settle_conflict_activated',
            field=models.BooleanField(default=False),
        ),
    ]
