# Generated by Django 3.2.20 on 2023-11-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0021_paysofterpromise_is_settle_conflict_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysofterpromise',
            name='settle_conflict_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=16, null=True),
        ),
    ]
