# Generated by Django 3.2.20 on 2023-11-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0022_paysofterpromise_settle_conflict_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysofterpromise',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
