# Generated by Django 3.2.20 on 2023-11-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0023_paysofterpromise_is_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysofterpromise',
            name='status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Fulfilled', 'Fulfilled'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Processing', max_length=100, null=True),
        ),
    ]
