# Generated by Django 3.2.20 on 2023-11-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0024_alter_paysofterpromise_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysofterpromise',
            name='service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=16, null=True),
        ),
    ]
