# Generated by Django 3.2.20 on 2023-12-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0025_paysofterpromise_service_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysofterpromise',
            name='payment_provider',
            field=models.CharField(choices=[('Paysofter', 'Paysofter'), ('Mastercard', 'Mastercard'), ('Verve', 'Verve'), ('Visa', 'Visa'), ('GTB', 'GTB'), ('Fidelity', 'Fidelity')], default='Paysofter', max_length=100),
        ),
    ]
