# Generated by Django 3.2.20 on 2023-12-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0026_alter_paysofterpromise_payment_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysofterpromise',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Debit Card', 'Debit Card'), ('Paysofter Account Fund', 'Paysofter Account Fund'), ('Paysofter Promise', 'Paysofter Promise'), ('Bank', 'Bank'), ('Transfer', 'Transfer'), ('QR COde', 'QR COde'), ('USSD', 'USSD')], default='Paysofter Promise', max_length=100, null=True),
        ),
    ]
