# Generated by Django 3.2.20 on 2024-02-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0031_auto_20240218_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysofterpromise',
            name='buyer_msg_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paysofterpromise',
            name='seller_msg_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
