# Generated by Django 3.2.20 on 2024-03-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0034_paysofterpromise_promise_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paysofterpromise',
            old_name='promise_msg',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='paysofterpromise',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
