# Generated by Django 3.2.20 on 2024-03-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0035_auto_20240320_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysofterpromise',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
