# Generated by Django 3.2.20 on 2024-07-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0036_alter_paysofterpromise_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysofterpromise',
            name='promise_id',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
    ]
