# Generated by Django 3.2.20 on 2024-07-21 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promise', '0037_alter_paysofterpromise_promise_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPaysofterPromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=16, null=True)),
                ('currency', models.CharField(blank=True, choices=[('NGN', 'NGN'), ('USD', 'USD'), ('CAD', 'CAD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('GHS', 'GHS'), ('INR', 'INR'), ('CNY', 'CNY'), ('ZAR', 'ZAR'), ('AED', 'United Arab Emirates Dirham'), ('AUD', 'Australian Dollar'), ('BRL', 'Brazilian Real'), ('JPY', 'Japanese Yen'), ('KES', 'Kenyan Shilling'), ('SAR', 'Saudi Riyal'), ('AFN', 'Afghan Afghani'), ('ALL', 'Albanian Lek'), ('AMD', 'Armenian Dram'), ('ANG', 'Netherlands Antillean Guilder'), ('AOA', 'Angolan Kwanza'), ('ARS', 'Argentine Peso'), ('AWG', 'Aruban Florin'), ('AZN', 'Azerbaijani Manat'), ('BAM', 'Bosnia-Herzegovina Convertible Mark'), ('BBD', 'Barbadian Dollar'), ('BDT', 'Bangladeshi Taka'), ('BGN', 'Bulgarian Lev'), ('BHD', 'Bahraini Dinar'), ('BIF', 'Burundian Franc'), ('BMD', 'Bermudian Dollar'), ('BND', 'Brunei Dollar'), ('BOB', 'Bolivian Boliviano'), ('BSD', 'Bahamian Dollar'), ('BTN', 'Bhutanese Ngultrum'), ('BWP', 'Botswanan Pula'), ('BYN', 'Belarusian Ruble'), ('BZD', 'Belize Dollar'), ('CDF', 'Congolese Franc'), ('CHF', 'Swiss Franc'), ('CLP', 'Chilean Peso'), ('COP', 'Colombian Peso'), ('CRC', 'Costa Rican Colón'), ('CUP', 'Cuban Peso'), ('CVE', 'Cape Verdean Escudo'), ('CZK', 'Czech Republic Koruna'), ('DJF', 'Djiboutian Franc'), ('DKK', 'Danish Krone'), ('DOP', 'Dominican Peso'), ('DZD', 'Algerian Dinar'), ('EGP', 'Egyptian Pound'), ('ERN', 'Eritrean Nakfa'), ('ETB', 'Ethiopian Birr'), ('FJD', 'Fijian Dollar'), ('FKP', 'Falkland Islands Pound'), ('FOK', 'Faroe Islands Króna'), ('GEL', 'Georgian Lari'), ('GGP', 'Guernsey Pound'), ('GIP', 'Gibraltar Pound'), ('GMD', 'Gambian Dalasi'), ('GNF', 'Guinean Franc'), ('GTQ', 'Guatemalan Quetzal'), ('GYD', 'Guyanaese Dollar'), ('HKD', 'Hong Kong Dollar'), ('HNL', 'Honduran Lempira'), ('HRK', 'Croatian Kuna'), ('HTG', 'Haitian Gourde'), ('HUF', 'Hungarian Forint'), ('IDR', 'Indonesian Rupiah'), ('ILS', 'Israeli New Shekel'), ('IMP', 'Isle of Man Pound'), ('IQD', 'Iraqi Dinar'), ('IRR', 'Iranian Rial'), ('ISK', 'Icelandic Króna'), ('JEP', 'Jersey Pound'), ('JMD', 'Jamaican Dollar'), ('JOD', 'Jordanian Dinar'), ('KGS', 'Kyrgystani Som'), ('KHR', 'Cambodian Riel'), ('KID', 'Kiribati Dollar'), ('KWD', 'Kuwaiti Dinar'), ('KYD', 'Cayman Islands Dollar'), ('KZT', 'Kazakhstani Tenge'), ('LAK', 'Laotian Kip'), ('LBP', 'Lebanese Pound'), ('LKR', 'Sri Lankan Rupee'), ('LRD', 'Liberian Dollar'), ('LSL', 'Lesotho Loti'), ('LYD', 'Libyan Dinar'), ('MAD', 'Moroccan Dirham'), ('MDL', 'Moldovan Leu'), ('MGA', 'Malagasy Ariary'), ('MKD', 'Macedonian Denar'), ('MMK', 'Myanma Kyat'), ('MNT', 'Mongolian Tugrik'), ('MOP', 'Macanese Pataca'), ('MRU', 'Mauritanian Ouguiya'), ('MUR', 'Mauritian Rupee'), ('MVR', 'Maldivian Rufiyaa'), ('MWK', 'Malawian Kwacha'), ('MXN', 'Mexican Peso'), ('MYR', 'Malaysian Ringgit'), ('MZN', 'Mozambican Metical'), ('NAD', 'Namibian Dollar'), ('NIO', 'Nicaraguan Córdoba'), ('NOK', 'Norwegian Krone'), ('NPR', 'Nepalese Rupee'), ('NZD', 'New Zealand Dollar'), ('OMR', 'Omani Rial'), ('PAB', 'Panamanian Balboa'), ('PEN', 'Peruvian Nuevo Sol'), ('PGK', 'Papua New Guinean Kina'), ('PHP', 'Philippine Peso'), ('PKR', 'Pakistani Rupee'), ('PLN', 'Polish Złoty'), ('PYG', 'Paraguayan Guarani'), ('QAR', 'Qatari Rial'), ('RON', 'Romanian Leu'), ('RSD', 'Serbian Dinar'), ('RUB', 'Russian Ruble'), ('RWF', 'Rwandan Franc'), ('SBD', 'Solomon Islands Dollar'), ('SCR', 'Seychellois Rupee'), ('SDG', 'Sudanese Pound'), ('SEK', 'Swedish Krona'), ('SGD', 'Singapore Dollar'), ('SHP', 'Saint Helena Pound'), ('SLL', 'Sierra Leonean Leone'), ('SOS', 'Somali Shilling'), ('SRD', 'Surinamese Dollar'), ('SSP', 'South Sudanese Pound'), ('STN', 'São Tomé and Príncipe Dobra'), ('SYP', 'Syrian Pound'), ('SZL', 'Swazi Lilangeni'), ('TJS', 'Tajikistani Somoni'), ('TMT', 'Turkmenistani Manat'), ('TND', 'Tunisian Dinar'), ('TOP', 'Tongan Paʻanga'), ('TRY', 'Turkish Lira'), ('TTD', 'Trinidad and Tobago Dollar'), ('TVD', 'Tuvaluan Dollar'), ('TWD', 'New Taiwan Dollar'), ('TZS', 'Tanzanian Shilling'), ('UAH', 'Ukrainian Hryvnia'), ('UGX', 'Ugandan Shilling'), ('UYU', 'Uruguayan Peso'), ('UZS', 'Uzbekistan Som'), ('VES', 'Venezuelan Bolívar'), ('VND', 'Vietnamese Đồng'), ('VUV', 'Vanuatu Vatu'), ('WST', 'Samoan Tala'), ('XAF', 'Central African CFA Franc'), ('XCD', 'Eastern Caribbean Dollar'), ('XDR', 'Special Drawing Rights'), ('XOF', 'West African CFA franc'), ('XPF', 'CFP Franc'), ('YER', 'Yemeni Rial'), ('ZMW', 'Zambian Kwacha')], default='NGN', max_length=50, null=True)),
                ('duration', models.CharField(blank=True, choices=[('0 day', '0 day'), ('Within 1 day', 'Within 1 day'), ('2 days', 'Less than 2 days'), ('3 days', 'Less than 3 days'), ('5 days', 'Less than 5 days'), ('1 week', 'Less than 1 week'), ('2 weeks', 'Less than 2 weeks'), ('1 month', 'Less than 1 month')], default='Within 1 day', max_length=100, null=True)),
                ('duration_hours', models.DurationField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Fulfilled', 'Fulfilled'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Processing', max_length=100, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('buyer_promise_fulfilled', models.BooleanField(default=False)),
                ('seller_fulfilled_promise', models.BooleanField(default=False)),
                ('is_settle_conflict_activated', models.BooleanField(default=False)),
                ('settle_conflict_charges', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=16, null=True)),
                ('service_charge', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=16, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Debit Card', 'Debit Card'), ('Paysofter Account Fund', 'Paysofter Account Fund'), ('Paysofter Promise', 'Paysofter Promise'), ('Bank', 'Bank'), ('Transfer', 'Transfer'), ('QR COde', 'QR COde'), ('USSD', 'USSD')], default='Paysofter Promise', max_length=100, null=True)),
                ('payment_provider', models.CharField(choices=[('Paysofter', 'Paysofter'), ('Mastercard', 'Mastercard'), ('Verve', 'Verve'), ('Visa', 'Visa'), ('GTB', 'GTB'), ('Fidelity', 'Fidelity')], default='Paysofter', max_length=100)),
                ('message', models.TextField(blank=True, max_length=225, null=True)),
                ('buyer_msg_count', models.PositiveIntegerField(default=0)),
                ('seller_msg_count', models.PositiveIntegerField(default=0)),
                ('promise_id', models.CharField(editable=False, max_length=50, null=True, unique=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promise_payer_test', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promise_seller_test', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
