# Generated by Django 3.2.20 on 2024-07-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0038_testpaysofterpromise'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaysofterpromise',
            name='buyer_email',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
