# Generated by Django 3.2.20 on 2024-08-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0040_paysofterpromise_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysofterpromise',
            name='product_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='paysofterpromise',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
