# Generated by Django 3.2.20 on 2023-09-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referred_users',
        ),
    ]
