# Generated by Django 3.2.20 on 2023-09-24 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referral', '0002_remove_referral_referred_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referred_users',
            field=models.ManyToManyField(related_name='referred_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
