# Generated by Django 3.2.20 on 2023-09-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendbuyeremail',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sendbuyeremail',
            name='payment_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sendselleremail',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sendselleremail',
            name='payment_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
