# Generated by Django 3.2.20 on 2023-09-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
