# Generated by Django 3.2.20 on 2023-09-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncreditcard',
            name='expiration_year',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
