# Generated by Django 3.2.20 on 2023-09-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transactioncreditcard_expiration_month_yaer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactioncreditcard',
            old_name='expiration_month_yaer',
            new_name='expiration_month_year',
        ),
    ]
