# Generated by Django 3.2.20 on 2023-09-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20230924_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtransaction',
            name='buyer_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
