# Generated by Django 3.2.20 on 2023-09-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_transaction_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payout_status',
            field=models.BooleanField(default=False),
        ),
    ]
