# Generated by Django 3.2.20 on 2023-10-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_transaction_payout_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncreditcard',
            name='card_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncreditcard',
            name='cvv',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncreditcard',
            name='expiration_month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncreditcard',
            name='expiration_month_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncreditcard',
            name='expiration_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
