# Generated by Django 3.2.20 on 2023-10-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_auto_20231025_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtransaction',
            name='payment_id',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='testtransaction',
            name='transaction_id',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
    ]
