# Generated by Django 3.2.20 on 2023-10-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_auto_20231028_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncreditcard',
            name='expiration_month',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncreditcard',
            name='expiration_month_year',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncreditcard',
            name='expiration_year',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
