# Generated by Django 3.2.20 on 2023-11-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_auto_20231028_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncreditcard',
            name='card_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncreditcard',
            name='cvv',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncreditcard',
            name='expiration_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncreditcard',
            name='expiration_month_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncreditcard',
            name='expiration_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
