# Generated by Django 3.2.20 on 2023-11-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_auto_20231104_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='buyer_email',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
