# Generated by Django 3.2.20 on 2023-11-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_alter_transaction_buyer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=16, null=True),
        ),
    ]
