# Generated by Django 3.2.20 on 2024-02-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_auto_20231118_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
