# Generated by Django 3.2.20 on 2024-08-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0018_auto_20240718_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtransaction',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='testtransaction',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
