# Generated by Django 3.2.20 on 2024-08-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0019_auto_20240817_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtransaction',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
