# Generated by Django 3.2.20 on 2024-08-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0020_auto_20240822_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtransaction',
            name='product_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='testtransaction',
            name='reference_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
