# Generated by Django 3.2.20 on 2024-03-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportticket_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportresponse',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='supportticket',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='admin_user_msg_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user_msg_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
