# Generated by Django 3.2.20 on 2024-03-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20240321_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportresponse',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
