# Generated by Django 3.2.20 on 2024-02-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencychoice',
            name='currency',
            field=models.CharField(blank=True, choices=[('NGN', 'Nigerian Naira'), ('USD', 'United States Dollar'), ('GBP', 'British Pound Sterling'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('ZAR', 'South African Rand'), ('BRL', 'Brazilian Real'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi'), ('AED', 'United Arab Emirates Dirham'), ('SAR', 'Saudi Riyal'), ('GBP', 'British Pound Sterling')], default='USD', max_length=3, null=True),
        ),
    ]
