# Generated by Django 3.2.20 on 2023-10-01 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('trading_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_reg_num', models.CharField(blank=True, max_length=50, null=True)),
                ('business_address', models.CharField(blank=True, max_length=225, null=True)),
                ('business_type', models.CharField(blank=True, choices=[('registered', 'Registered'), ('unregistered', 'Unregistered')], max_length=225, null=True)),
                ('staff_size', models.CharField(blank=True, choices=[('small', 'Small (1-50 employees)'), ('medium', 'Medium (51-250 employees)'), ('large', 'Large (251+ employees)')], max_length=50, null=True)),
                ('business_industry', models.CharField(blank=True, choices=[('it', 'Information Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('education', 'Education'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('services', 'Services'), ('entertainment', 'Entertainment'), ('food', 'Food & Beverage'), ('travel', 'Travel & Tourism'), ('real_estate', 'Real Estate'), ('construction', 'Construction'), ('automotive', 'Automotive'), ('agriculture', 'Agriculture'), ('energy', 'Energy'), ('environmental', 'Environmental'), ('government', 'Government'), ('nonprofit', 'Nonprofit'), ('other', 'Other')], max_length=50, null=True)),
                ('business_category', models.CharField(blank=True, choices=[('startup', 'Startup'), ('small_business', 'Small Business'), ('medium_business', 'Medium Business'), ('large_business', 'Large Business'), ('corporation', 'Corporation'), ('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('franchise', 'Franchise'), ('family_owned', 'Family Owned'), ('online_business', 'Online Business'), ('brick_and_mortar', 'Brick and Mortar'), ('service_provider', 'Service Provider'), ('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('manufacturer', 'Manufacturer'), ('restaurant', 'Restaurant'), ('hospitality', 'Hospitality'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('tech', 'Tech'), ('creative', 'Creative'), ('entertainment', 'Entertainment'), ('travel', 'Travel'), ('construction', 'Construction'), ('automotive', 'Automotive'), ('agriculture', 'Agriculture'), ('energy', 'Energy'), ('environmental', 'Environmental'), ('government', 'Government'), ('nonprofit', 'Nonprofit'), ('other', 'Other')], max_length=50, null=True)),
                ('business_description', models.TextField(blank=True, max_length=225, null=True)),
                ('business_website', models.CharField(blank=True, max_length=225, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_account_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
