# Generated by Django 3.2.20 on 2023-09-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20230921_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_secret_key',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
