# Generated by Django 3.2.20 on 2023-09-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_user_api_secret_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='api_secret_key',
            new_name='live_api_secret_key',
        ),
        migrations.AddField(
            model_name='user',
            name='test_api_secret_key',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
