# Generated by Django 3.2.20 on 2023-09-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20230921_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='live_api_key',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='live_api_secret_key',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='test_api_key',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='test_api_secret_key',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
