# Generated by Django 3.2.20 on 2023-09-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20230924_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_id',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
