# Generated by Django 3.2.20 on 2023-09-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_user_account_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_related_name': 'user'},
        ),
    ]
