# Generated by Django 3.2.20 on 2023-11-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_user_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_code',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
    ]
