# Generated by Django 3.2.20 on 2023-11-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_user_security_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_code',
            field=models.CharField(editable=False, max_length=4, null=True, unique=True),
        ),
    ]
