# Generated by Django 3.2.20 on 2023-11-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20231118_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='live_api_key',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='live_api_secret_key',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_link',
            field=models.CharField(editable=False, max_length=225, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='test_api_key',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='test_api_secret_key',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True),
        ),
    ]
