# Generated by Django 3.2.20 on 2023-12-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_user_is_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_live_mode',
            new_name='is_api_key_live',
        ),
    ]
