# Generated by Django 3.2.20 on 2023-12-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_rename_is_live_mode_user_is_api_key_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_usd_selected',
            field=models.BooleanField(default=False),
        ),
    ]
