# Generated by Django 3.2.20 on 2024-07-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_payout_choice',
            field=models.CharField(blank=True, choices=[('Paysofter Account Fund', 'Paysofter Account Fund'), ('Bank', 'Bank')], default='Bank', max_length=100, null=True),
        ),
    ]
