# Generated by Django 3.2.20 on 2024-08-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0020_user_seller_payout_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_id',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
    ]
