# Generated by Django 3.2.20 on 2024-08-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0021_user_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_seller_account_verified',
            field=models.BooleanField(default=False),
        ),
    ]
