# Generated by Django 3.2.20 on 2024-08-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0022_user_is_seller_account_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_seller_account_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
